name: Feature

on:
  push:
    branches:
      - Feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile
        run: javac -cp . src/manager/*.java src/model/*.java src/model/**/*.java src/test/*.java src/view/*.java

      - run: |
             javac -cp lib/*:out -d testout test/*.java
             java -cp lib/*:out:testout org.junit.runner.JUnitCore TestSuite
      
