name: Feature

on:
  push:
    branches:
      - Feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'
          distribution: 'corretto'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile
        run: javac -d out/ src/*.java

      - name: Run unit tests
        run: java -cp out org.junit.runner.JUnitCore src.test.TestSuite

