name: Feature

on:
  push:
    branches:
      - Feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile
        run: javac -cp lib/junit-4.13.1.jar -d out src/manager/*.java src/model/*.java src/model/**/*.java src/test/*.java src/view/*.java

      - name: Run unit tests
        run: java -cp .:lib/junit-4.13.1.jar:out org.junit.runner.JUnitCore src.test.TestSuite

      
