name: JaCoCo Code Coverage

on:
  push:
    branches: [ "Feature_NewCIMaven" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true

      - name: Construir y empaquetar con Maven
        run: mvn package

      - name: Guardar el ejecutable .jar como artefacto
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: target/my-app.jar